### ISSUE TITLE
How do I set the expected value from 0 to infinity?

### ISSUE THREAD

**Issue by doox911** [JetBrains/phpstorm-attributes#11]
How can I use the `#[ExpectedValues]` attribute to indicate that a method or function argument can be 0 or more? And it can only be an integer.

I would like something like this:

```php

#[ExpectedValues([0,1, ...])]
public function test(int $arg) {}
```

**Comment by wbars** [comment]
Hello, this feature request is out of scope of the `#[ExpectedValues]` design. The attribute goal is to enumerate finite number of expected values.
