### ISSUE TITLE
[ArrayShape] Document how to set the type to nullable or even join / intersection type

### ISSUE THREAD

**Issue by Neirda24** [JetBrains/phpstorm-attributes#14]
There is nothing in the README that states how to set the type nullable or use a join / intersection type.
I assume it is the same as for phpdoc so `'?' . DateTime::class` for example.

Because I also have a problem with https://github.com/JetBrains/phpstorm-attributes/issues/13 I cannot test it.

**Comment by wbars** [comment]
Please try "DateTime|null"

**Comment by Neirda24** [comment]
Ok since the linked issue was not a real one I think it should be working. I'll update it and close it as soon as I'll be able to test it. Thank you.
