### ISSUE TITLE
Again with Attributes

### ISSUE THREAD

**Issue by ghost** [JetBrains/phpstorm-attributes#16]
Hello guys first and foremost sorry for my bad English, but not is my primary language.

`PHP Attributes` are supported by PHPStorm and the downloadable package in this github allows users to provide attributes even to those who use IDEs different from PHPStorm.

The question at this point is only one.

If I want to define custom `Attributes` how can I tell PHPStorm not to use its built-in?

In the `Settings->Inspection` section I saw that it is possible to disable the inspection, but in doing so the help that PHPStorm gives to programmers during the inspection phase is lost by signaling when it would be useful/necessary to use an Attribute.

Wouldn't it be possible to make the inspection go further in the case of a `Custom Attribute` by merely indicating that that method or property needs an attribute?

I believe that allowing developers to harness the power of PHPStorm inspection by allowing them to customize attributes would be a very useful feature.

At the moment if I assign a custom attribute to a method or property PHPStorm keeps saying that it wants to use its built-in.

I hope I have explained myself in an understandable way.

I wish you a good job, keep it up.

Adriano

**Comment by wbars** [comment]
Hello! Can you please share a particular code example that doesn't work in the way you expect?

**Comment by ghost** [comment]
Surely.

I will be happy to attach the screenshot

![Cattura](https://user-images.githubusercontent.com/14064365/140184855-b2c22659-b66c-4d6c-b241-3dd6cfa731ac.PNG)

In the simple example shown above, as you can see I have defined a custom Attribute called `Custom`, then applying it to the method reported by the PHPStorm inspection, but the PHPStorm inspection keeps saying that I should add the `Pure` attribute.

Thanks for your assistance and patience.
Adriano

**Comment by wbars** [comment]
Thank you. Unfortunately, for now, there is no way to make it work in the way you described rather than disabling inspection altogether or suppressing it in this doc comment. I've created an issue to discuss, please follow https://youtrack.jetbrains.com/issue/WI-63869.

**Comment by ghost** [comment]
Thanks for your assistance, I will definitely follow it.
