### ISSUE TITLE
Specify two ArrayShapes for a function.

### ISSUE THREAD

**Issue by tecnologiaterabyte** [JetBrains/phpstorm-attributes#17]
Hi, its posible specify two ArrayShapes for a function.

```php
public function text(array $attributes = [], array $config = []): self
```

I would like to specify the attributes for each array try:

```php
#[ArrayShape(['attributes' => ['dirname' => 'string'], 'config' => ['key' => int]])]
public function text(array $attributes = [], array $config = []): self
```

But it didn't work thanks for the help.

**Comment by wbars** [comment]
Hello! There is a feature request for such functionality at https://youtrack.jetbrains.com/issue/WI-56033, please follow it for the updates.
