### ISSUE TITLE
Using `ExpectedValues` attribute with a splat argument

### ISSUE THREAD

**Issue by amiranagram** [JetBrains/phpstorm-attributes#19]
Hi, is it currently possible to define expected values in a function where the argument has a splat operator (`...`).

For example:

```php
/**
 * @param  string ...$permissions
 * @return bool
 */
public function hasPermissionTo(
    #[ExpectedValues(['view users', 'create users', 'etc'])]
    ...$permissions
): bool
{
    //
}
```

Currently, I'm seeing code completion only when adding the first argument. After that, nothing.

![image](https://user-images.githubusercontent.com/38536188/162531980-5220d6fb-a897-4e33-b6a1-89b4d0c406d7.png)

![image](https://user-images.githubusercontent.com/38536188/162531859-b3b4689a-87e3-447f-bae4-40945d24426c.png)

**Comment by wbars** [comment]
Hello! Indeed it's a bug, thanks for the reporting! I've moved it to our issue tracker, please follow the issue there: https://youtrack.jetbrains.com/issue/WI-66090
