### ISSUE TITLE
How about #[Internal]?

### ISSUE THREAD

**Issue by dsentker** [JetBrains/phpstorm-attributes#2]
Similar to the @internal Annotation it would be useful to mark classes and methods for internal use (limited scope) only. The annotation is currently only supported for classes, not methods.

**Comment by wbars** [comment]
Hello. While your suggestion surely make sense, I think this is not exactly use case for these particular attributes ATM. `@internal` PhpDoc already widely used and even somewhat documented in https://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.internal.pkg.html. 
Also I don't see what additional opportunities migrating this to attributes will open to users (in `@deprecated` for example we now able to provide more metadata using attributes).

I will decline this proposal for now, but these may be reconsidered in future. Thank you for the suggestion.
