### ISSUE TITLE
[ArrayShape] Cannot prompt using constants

### ISSUE THREAD

**Issue by boyfoo** [JetBrains/phpstorm-attributes#20]
this is normal

![image](https://user-images.githubusercontent.com/29603067/181677680-ec248292-7795-4aa1-8261-aebea9f7ea11.png)

But I define it as a constant, he can't code hint

![image](https://user-images.githubusercontent.com/29603067/181677864-66616f89-4a9d-4dc4-8795-0a8669d6e8a8.png)

My phpstorm is installed on windows11, the version is PhpStorm 2022.1.4

**Comment by bleuscyther** [comment]
There is a ticket about this on Youtrack

https://youtrack.jetbrains.com/issue/WI-56028/ArrayShape-sometimes-doesnt-resolve-the-type-correctly-if-shape-is-specified-via-constant

**Comment by wbars** [comment]
Indeed, there is an issue for this https://youtrack.jetbrains.com/issue/WI-56028/ArrayShape-sometimes-doesnt-resolve-the-type-correctly-if-shape-is-specified-via-constant. I will add this specific case as comment though, thanks.
