### ISSUE TITLE
Can we get a release?

### ISSUE THREAD

**Issue by laurinkeithdavis** [JetBrains/phpstorm-attributes#28]
PHPStan is flagging items like this because the only tag in this project does not include all of the changes.
![image](https://github.com/JetBrains/phpstorm-attributes/assets/75857/b3120930-6bd1-40d0-aef2-59ca29d2e6dd)

**Comment by pronskiy** [comment]
Thanks for bringing this up. Tagged: https://github.com/JetBrains/phpstorm-attributes/releases/tag/1.1
