### ISSUE TITLE
PhpStorm complains about multiple definitions when installing this package

### ISSUE THREAD

**Issue by WoutervdBrink** [JetBrains/phpstorm-attributes#6]
Today I installed PhpStorm 2020.3 and noticed this package - awesome! Works as expected and I like how the IDE proposes to add the correct attributes when it believes it's required, like for `Pure` and `Immutable`.

However, to ensure my code base is also compatible with non-PhpStorm environments, I've also installed this package with `composer require --dev jetbrains/phpstorm-attributes` and now PhpStorm complains how there are multiple definitions for the attribute classes I use: "Multiple definitions exist for class 'Immutable'". It detects both the class loaded via PhpStorm and the class loaded via Composer in the `vendor` directory.

Is there any way to convince PhpStorm to use either?

**Comment by wbars** [comment]
Hello. This is valid request, I've created an issue https://youtrack.jetbrains.com/issue/WI-57392, thanks.

**Comment by WoutervdBrink** [comment]
Thank you!
