### ISSUE TITLE
Using attributes with PHP < 8.0

### ISSUE THREAD

**Issue by Mopolo** [JetBrains/phpstorm-attributes#7]
Hi!

On the anouncement page it says that some of these attributes work on older versions of PHP if used on a single line (so that PHP thinks they are comments).

However if PHPStorm is configured to sync settings with this `composer.json`:

```json
{
    "require": {
        "php": "^7.4 | ^8.0"
    },
    "autoload": {
        "psr-4": {
            "Acme\\": "src"
        }
    }
}
```

Then the attribute is shown with an error:

<img width="375" alt="image" src="https://user-images.githubusercontent.com/1319234/101641363-f4373780-3a31-11eb-97f1-374bb3d51747.png">

And the error:

<img width="724" alt="image" src="https://user-images.githubusercontent.com/1319234/101641439-07e29e00-3a32-11eb-852f-a8b85cd10074.png">

At the same time the attribute works in other code:

<img width="716" alt="image" src="https://user-images.githubusercontent.com/1319234/101641497-1af56e00-3a32-11eb-9c19-569eaebcb650.png">

Is that the indented behavior?

**Comment by wbars** [comment]
Hey. These attributes works for PHP < 8 as side effect of the fact that one-line version of attribute will be parsed as line comment in some cases, generally it's recommended to use them with PHP 8 version. Generally attributes is PHP 8 language feature and this inspection aims to hint users about that fact.

**Comment by Mopolo** [comment]
Hi thanks for the reply. I understand the behaviour it's just a shame since it explicitly says that it works in PHP 7.4 on the release page of PHPStorm: https://www.jetbrains.com/phpstorm/whatsnew/

<img width="491" alt="image" src="https://user-images.githubusercontent.com/1319234/101763164-b47a5980-3ade-11eb-90cc-a5f8d224d76a.png">


These are PHPStorm specific attributes so it would make sens for them to work on lower versions (well they do but with a big red warning).

I'll just use them in PHP 8 instead. Thanks.

**Comment by andyvenus** [comment]
Bit late to the party, but it would be nice if these weren't marked as errors as it's valid PHP code. Are we able to disable that inspection? I can't find it if so.
