### ISSUE TITLE
Please use semver

### ISSUE THREAD

**Issue by LastDragon-ru** [JetBrains/phpstorm-attributes#8]
Semver is the standard for PHP: https://semver.org/

**Comment by wbars** [comment]
Thanks for suggestion. Could you elaborate how would benefit from Semver in this specific package considering the fact that expected rate of updates will be rare?

**Comment by LastDragon-ru** [comment]
Following the standard is not enough? :)

**Comment by wbars** [comment]
Thank you for the suggestion. We will consider this if our versioning will bring any real troubles.
